
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grpsxolrhkerxgzrnmaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycHN4b2xyaGtlcnhnenJubWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTEzNTEsImV4cCI6MjA2MjEyNzM1MX0.BO2v44M5TIrpjd1ZpABkl8eNfX8_wJnvD8Kc3Xrpc2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
